# Generated by Django 5.2.1 on 2025-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0003_auto_20260502_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=100),
        ),
    ]
