# Generated by Django 5.2.1 on 2025-05-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0005_vacancy_delete_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.AddField(
            model_name='sale',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=100),
        ),
    ]
