-- +goose Up
CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    client_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'new',
    from_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    from_lon DOUBLE PRECISION NOT NULL DEFAULT 0,
    to_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    to_lon DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE IF EXISTS orders;
